### PR TITLE
LPS-172656 Move AsahUtil.isAnalyticsEnabled to AnalyticsSettingsManager

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======

The main goal of this PR is start the duplication of code between AnalyticsSettingsManager and other tools we currently have, like AsahUtil.

[Link to story](https://issues.liferay.com/browse/LPS-171785)
[Link to subtask](https://issues.liferay.com/browse/LPS-172656)

Proposed Solution
========

Delete AsahUtil.isAnalyticsEnabled(companyId,groupId) and use the AnalyticsSettingsManager instead

Steps to Verify:
----------------
No functional test included in this PR.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Ups!! I miss some sf problem, I will fix it and push the change to this PR

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
