### PR TITLE
LRAC-12415 remove feature flag

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
Hi Riccardo, I'm removing the feature flag to enable batch syncing. Can you take a look if the classes & modules i removed are not used (i removed one [dependency](https://github.com/riccardo-ferrari/liferay-portal/commit/f65bfb7bc6351d4e86b8c49ad1058d31e6c433b7#diff-c89d5158fce6ffbe80760142b70214dd256a3b94e4637492bdc0aed6eb0153c5L17) in commerce module)? Thanks!

I ran ci:test:relevant and i got errors, but i'm not sure how my changes could break these:

[com.liferay.analytics.settings.rest.internal.manager.test.AnalyticsSettingsManagerTest](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327077/testReport/com.liferay.analytics.settings.rest.internal.manager.test/AnalyticsSettingsManagerTest) - [Failed 2 of last 11](https://testray.liferay.com/home/-/testray/case_results/2098397574/history)
        [testGetSiteIds](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327077//testReport/com.liferay.analytics.settings.rest.internal.manager.test/AnalyticsSettingsManagerTest/testGetSiteIds)
        [testUpdateCompanyConfiguration](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/327077//testReport/com.liferay.analytics.settings.rest.internal.manager.test/AnalyticsSettingsManagerTest/testUpdateCompanyConfiguration)

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
@rachaelkoestartyo, LGTM!

https://github.com/riccardo-ferrari/liferay-portal/pull/53/commits/c841eee87c18fc4c02600108fd02753c55346c76 any plan to update it to the AnalyticsCloudClient that is using portal.kernel.http instead of httpclient for connecting to AC?

**Comment by rachaelkoestartyo** [comment]
oh didn't see your comment. since you were on PTO so i resent to marcos 😄. i'll take a look at using portal.kernel.http.

**Pull request closed without merging**
